require_relative "strategy" # typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sisakulint < Formula
  desc "Support tools for GitHub Actions workflow files"
  homepage "https://github.com/sisaku-security/sisakulint"
  version "0.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.3.3/sisakulint_0.3.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6c54dd5be251c5aaa07b26a409aef68a33505ae1b770427c9233b06ce27d2579"

      define_method(:install) do
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.3.3/sisakulint_0.3.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "95247135d5c902c8d0c755fa43c9d0746eafe0da2c9e5f76d72dd20f83f980da"

      define_method(:install) do
        bin.install "sisakulint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.3.3/sisakulint_0.3.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1d65e1767795bbb03b2fe88faa2fe60aa5e5f6749e961003de87cd5e00864e81"
      define_method(:install) do
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.3.3/sisakulint_0.3.3_linux_armv6.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1c5d11f7e60a6d553c330389df7f10f8e4891b0df0e6d975abe13dd3d1b3e78b"
      define_method(:install) do
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.3.3/sisakulint_0.3.3_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c686f3965aa844b36a9328e2a56a2fc8d2c62b0f045bccdc872cc610e3b8c519"
      define_method(:install) do
        bin.install "sisakulint"
      end
    end
  end

  test do
    system "#{bin}/sisakulint -version"
  end
end
