# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sisakulint < Formula
  desc "Support tools for GitHub Actions workflow files"
  homepage "https://github.com/sisaku-security/sisakulint"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.2/sisakulint_0.2.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c0f1a2f1e637cb62de225af653acfb6bb841be022d711aed658e35bacd468112"

      def install
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.2/sisakulint_0.2.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cada581588a740f8bb9592d4dccaa495f0baae1426ffc7a12dff1de3060598a5"

      def install
        bin.install "sisakulint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.2/sisakulint_0.2.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bddf0406eefa7cde35a8fa12f2b1064a33080e4d19ea3796b92330f0c30c7ee9"
      def install
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.2/sisakulint_0.2.2_linux_armv6.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6357ce0e65cd1586ff3850fc94d6ae72b877490e67cc78a26bb07d8e7e72f2af"
      def install
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.2/sisakulint_0.2.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "94a86e756038361f6d9e58a0dc47e26c4391a8054796f844d1e635ec53d37dd9"
      def install
        bin.install "sisakulint"
      end
    end
  end

  test do
    system "#{bin}/sisakulint -version"
  end
end
