# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sisakulint < Formula
  desc "Support tools for GitHub Actions workflow files"
  homepage "https://github.com/sisaku-security/sisakulint"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.4/sisakulint_0.2.4_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "02f18ab804362039574e9917fede72a102d0dbbb61cc682a22cbe531ca53e82a"

      def install
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.4/sisakulint_0.2.4_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bd8cf99e21b5f92db795cb5f6c9e6ecdfa36b8cb4ab75f20338e01756fcf5f08"

      def install
        bin.install "sisakulint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.4/sisakulint_0.2.4_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e1c362bda01d7534fe5f04ea56bb054ba690ac3f3fb4fe65c0ac25e9c9c506cd"
      def install
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.4/sisakulint_0.2.4_linux_armv6.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8f484526bd1be2e864954b833f1a77671ccc4232513625a084b0d34ea84e2e16"
      def install
        bin.install "sisakulint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sisaku-security/sisakulint/releases/download/v0.2.4/sisakulint_0.2.4_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "22ecd136e50b719b8b40cc9429f1840b8e032210ebcb644e5306d7afdcb1e329"
      def install
        bin.install "sisakulint"
      end
    end
  end

  test do
    system "#{bin}/sisakulint -version"
  end
end
